engines:
  eslint:
    enabled: true
    channel: "eslint-6"
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  fixme:
    enabled: true
